baseURL: "http://10xSwift.github.io/"
languageCode: "en-us"
defaultContentLanguage: "en"
title: "10xSwift"
theme: "mini"

math: true

paginate: 10

social:
  twitter: https://twitter.com/10xswift

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: xcode
    tabWidth: 2
